language: node_js
node_js:
- '6.11.0'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - npm install 

script:
  - npm run build

before_deploy:
  - cd "build"
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on:
    repo: karthikbalajikb/WD-Weather-App
  bucket: karthikbalajikb
  region: us-east-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: karthikbalajikb
  key: latest.zip
  bundle_type: zip
  application: WD-Weather-App
  deployment_group: WD-Travis-grp
  region: us-east-1
  on:
    repo: karthikbalajikb/WD-Weather-App

after_deploy:
  - echo "Performing after deploy procedures..."